name: Create Release and Publish to PyPI

on:
  push:
    branches:
      - main  # or your default branch name

permissions:
  contents: write
  packages: write

jobs:
  create-release-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # This ensures all tags are fetched

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools

    - name: Get version
      id: get_version
      run: |
        version=$(python setup.py --version)
        echo "VERSION=$version" >> $GITHUB_OUTPUT

    - name: Try to create tag
      id: create_tag
      continue-on-error: true
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag v${{ steps.get_version.outputs.VERSION }}
        git push origin v${{ steps.get_version.outputs.VERSION }}
        echo "TAG_CREATED=true" >> $GITHUB_OUTPUT

    - name: Create Release
      if: steps.create_tag.outputs.TAG_CREATED == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: true

    - name: Build package
      run: python -m build

    - name: Publish distribution to PyPI
      if: steps.create_tag.outputs.TAG_CREATED == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
